# Generated by Django 2.0 on 2019-04-17 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import swapper


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        swapper.dependency('dataframe_store', 'Label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'labels',
                'verbose_name': 'label',
                'abstract': False,
                'app_label': 'dataframe_store',
                'swappable': swapper.swappable_setting('dataframe_store', 'Label')
            },
        ),
    ]
