# Generated by Django 2.0.13 on 2019-09-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataframe_store', '0003_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbdataframe',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='dbdataframe',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='dbdataframe',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
